"""Updated the User and Book tables

Revision ID: 01d5a9668c4b
Revises: 
Create Date: 2025-05-06 23:21:49.284416

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '01d5a9668c4b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('book', schema=None) as batch_op:
        batch_op.add_column(sa.Column('title', sa.String(length=150), nullable=False))
        batch_op.add_column(sa.Column('author', sa.String(length=150), nullable=False))
        batch_op.add_column(sa.Column('genre', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('description', sa.Text(), nullable=True))

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('username', sa.String(length=150), nullable=False))
        batch_op.add_column(sa.Column('email', sa.String(length=150), nullable=True))
        batch_op.add_column(sa.Column('password', sa.String(length=128), nullable=False))
        batch_op.create_unique_constraint(None, ['email'])
        batch_op.create_unique_constraint(None, ['username'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('password')
        batch_op.drop_column('email')
        batch_op.drop_column('username')

    with op.batch_alter_table('book', schema=None) as batch_op:
        batch_op.drop_column('description')
        batch_op.drop_column('genre')
        batch_op.drop_column('author')
        batch_op.drop_column('title')

    # ### end Alembic commands ###
