"""Updated the tables

Revision ID: 1897735ad67e
Revises: 2832bb49884d
Create Date: 2025-05-06 23:50:49.481477

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1897735ad67e'
down_revision = '2832bb49884d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('book', schema=None) as batch_op:
        batch_op.add_column(sa.Column('google_id', sa.String(length=40), nullable=True))
        batch_op.add_column(sa.Column('cover_url', sa.String(length=300), nullable=True))
        batch_op.create_unique_constraint('uq_book_google_id', ['google_id'])

    with op.batch_alter_table('book_share', schema=None) as batch_op:
        batch_op.add_column(sa.Column('from_user_id', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('to_user_id', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('book_id', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('status', sa.String(length=30), nullable=False))
        batch_op.add_column(sa.Column('timestamp', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True))
        batch_op.create_foreign_key('fk_book_share_from_user', 'user', ['from_user_id'], ['id'])
        batch_op.create_foreign_key('fk_book_share_book', 'book', ['book_id'], ['id'])
        batch_op.create_foreign_key('fk_book_share_to_user', 'user', ['to_user_id'], ['id'])

    with op.batch_alter_table('user_book', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('book_id', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('status', sa.String(length=30), nullable=False))
        batch_op.add_column(sa.Column('date_added', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True))
        batch_op.add_column(sa.Column('date_completed', sa.DateTime(), nullable=True))
        batch_op.create_foreign_key('fk_user_book_book', 'book', ['book_id'], ['id'])
        batch_op.create_foreign_key('fk_user_book_user', 'user', ['user_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_book', schema=None) as batch_op:
        batch_op.drop_constraint('fk_user_book_book', type_='foreignkey')
        batch_op.drop_constraint('fk_user_book_user', type_='foreignkey')
        batch_op.drop_column('date_completed')
        batch_op.drop_column('date_added')
        batch_op.drop_column('status')
        batch_op.drop_column('book_id')
        batch_op.drop_column('user_id')

    with op.batch_alter_table('book_share', schema=None) as batch_op:
        batch_op.drop_constraint('fk_book_share_from_user', type_='foreignkey')
        batch_op.drop_constraint('fk_book_share_book', type_='foreignkey')
        batch_op.drop_constraint('fk_book_share_to_user', type_='foreignkey')
        batch_op.drop_column('timestamp')
        batch_op.drop_column('status')
        batch_op.drop_column('book_id')
        batch_op.drop_column('to_user_id')
        batch_op.drop_column('from_user_id')

    with op.batch_alter_table('book', schema=None) as batch_op:
        batch_op.drop_constraint('uq_book_google_id', type_='unique')
        batch_op.drop_column('cover_url')
        batch_op.drop_column('google_id')

    # ### end Alembic commands ###
