"""Add page_count column to the Book table

Revision ID: 4ecd91d09b8a
Revises: 1897735ad67e
Create Date: 2025-05-07 09:22:43.478275

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4ecd91d09b8a'
down_revision = '1897735ad67e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('book', schema=None) as batch_op:
        batch_op.add_column(sa.Column('page_count', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('book', schema=None) as batch_op:
        batch_op.drop_column('page_count')

    # ### end Alembic commands ###
